### Bet sainy tomorrow

POST http://localhost:3000/bet/

{
  "betId": "xxxx-xxx3",
  "title": "My Bet 3",
  "description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna.",
  "criteria": [
    { "title": "Rainy Tomorrow", "description": "", "probability": 1 },
    { "title": "sunny", "description": "", "probability": 0.5 },
    { "title": "snowy", "description": "", "probability": 0.1 }
  ],
  "expirationTime": "2022-08-15",
  "creator": {
    "userId": "xxxx-x10",
    "nickname": "Xedon",
    "mail": "emanuel.vollmer@mayflower.de"
  },
  "minimumWager": 40,
  "isWagerSelectable": false,
  "isPublic": true,
  "competitors": [
    {
      "userId": "xxxx-x13",
      "nickname": "Thomas",
      "mail": "thomas.schindler@mayflower.de",
      "wager": 40,
      "criteriaIndex": 0
    },
    {
      "userId": "xxxx-x10",
      "nickname": "Xedon",
      "mail": "emanuel.vollmer@mayflower.de",
      "wager": 40,
      "criteriaIndex": 1
    }
  ]
}


### Get Bet
GET http://localhost:3000/bet/a32508ac-04ec-5a44-83fd-4282b064909b

### Query all
GET http://localhost:3000/bet/

### Query by creatorId
GET http://localhost:3000/bet/?creatorId=a7eba72b-0f06-5eeb-a114-3f68d8425abd

### Query by competitorId
GET http://localhost:3000/bet/?competitorId=8b2662d9-4f3e-5f7a-b744-b650a86a244e


### Query by creatorMail
GET http://localhost:3000/bet/?creatorMail=emanuel.vollmer@mayflower.de


### Query by competitorMail
GET http://localhost:3000/bet/?competitorMail=thomas.schindler@mayflower.de

### Query by competitorMail
GET http://localhost:3000/bet/?competitorMail=emanuel.vollmer@mayflower.de


### Query by creatorMail
GET http://localhost:3000/bet/?creatorMail=thomas.schindler@mayflower.de

### Update Bet
PUT http://localhost:3000/bet/a32508ac-04ec-5a44-83fd-4282b064909b

{
  "creator": {
    "nickname": "Xedon",
    "mail": "emanuel.vollmer@mayflower.de",
    "userId": "a7eba72b-0f06-5eeb-a114-3f68d8425abd"
  },
  "competitors": [
    {
      "nickname": "Thomas",
      "wager": 101,
      "mail": "thomas.schindler@mayflower.de",
      "userId": "8b2662d9-4f3e-5f7a-b744-b650a86a244e"

      "criteriaIndex": 1
    },
    {
      "nickname": "Xedon",
      "wager": 101,
      "mail": "emanuel.vollmer@mayflower.de",
      "userId": "a7eba72b-0f06-5eeb-a114-3f68d8425abd"

      "criteriaIndex": 1
    },
    {
      "nickname": "Pati",
      "wager": 101,
      "mail": "patrick.shaikh@mayflower.de"

      "criteriaIndex": 1
    }
  ],
  "criteria": [
    { "title": "sunny", "description": "", "probability": 0.5 },
  ],
  "expirationTime": "2022-05-23",
  "betId": "a32508ac-04ec-5a44-83fd-4282b064909b",
  "description": "Rainy tomorrow",
  "isPublic": true,
  "title": "My Bet test",
  "minimumWager": 100
}